services:
  api-rest:
    build: .
    image: mic/api-rest:1.0.0
    container_name: api-rest
    ports:
      - "8003:8003"
    restart: always
    environment:
      - TZ=Asia/Bangkok
    env_file:
      - ../.env
    volumes:
      - ./log:/app/log
    networks:
      - mms-network

networks:
  mms-network:
    external: true
