services:

  postgres:
    image: postgres:17-trixie
    container_name: postgres
    mem_limit: 1g
    cpus: 0.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iiot_db
    ports:
      - 5432:5432
    restart: always
    networks:
      - mms-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
  
networks:
  mms-network:
    external: true