services:
  kong:
    container_name: kong
    image: kong:3.7.1
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8500, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_ADMIN_API_URI: http://127.0.0.1:8011
      KONG_ADMIN_GUI_API_URL: http://127.0.0.1:8011
      KONG_ADMIN_CORS: "on"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: /var/run/kong
    networks:
      - kong-net
      - mms-network
    ports:
      - "8500:8500/tcp"
      - "8443:8443/tcp"
      - "8011:8001/tcp"
      - "8012:8002/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    mem_limit: 1g
    cpus: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
    security_opt:
      - no-new-privileges

volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong-net:
    external: false
    ipam:
      config:
        - subnet: 172.1.1.0/24
  mms-network:
    external: true
