services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    mem_limit: 512m
    cpus: 0.5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:

      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 9000:9000  
    command: ["--no-setup-token"]

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network