services:
  api-sse:
    build: .
    image: mic/api-sse:1.0.0
    container_name: api-sse
    ports:
      - "8002:8002"
    restart: always
    environment:
      - TZ=Asia/Bangkok
    env_file:
      - ../.env
    volumes:
      - ./log:/app/log
    networks:
      - mms-network

networks:
  mms-network:
    external: true
