logger:
  level: INFO
  format: logfmt
  add_timestamp: true
metrics:
  prometheus: {}



input:
  label: kafka_input
  kafka:
    addresses: ["kafka:9092"]
    topics: ["data", "status", "alarm"]
    consumer_group: "benthos_clickhouse_group"
    start_from_oldest: true
    batching:
      period: 1s
      byte_size: 100000

output:
  switch:
    cases:
      - check: meta("kafka_topic") == "status"
        output:
          sql_insert:
            driver: clickhouse
            dsn: clickhouse://default:maibok@clickhouse:9000/default
            table: status_tb
            columns:
              - process
              - device
              - status
            args_mapping: |
              root = [
                this.process,
                this.device,
                this.payload.parse_json().catch({"status": this.payload}).status
              ]
            batching:
              count: 10000
              period: 1s

      - check: meta("kafka_topic") == "alarm"
        output:
          sql_insert:
            driver: clickhouse
            dsn: clickhouse://default:maibok@clickhouse:9000/default
            table: alarm_tb
            columns:
              - process
              - device
              - status
            args_mapping: |
              root = [
                this.process,
                this.device,
                this.payload.parse_json().catch({"status": this.payload}).status
              ]
            batching:
              count: 10000
              period: 1s

      - check: meta("kafka_topic") == "data"
        output:
          sql_insert:
            driver: clickhouse
            dsn: clickhouse://default:maibok@clickhouse:9000/default
            table: data_tb
            columns:
              - process
              - device
              - data1
              - model
            args_mapping: |
              let payload = this.payload.parse_json().catch({})
              root = [
                this.process,
                this.device,
                $payload.data1.number().catch(0.0),
                $payload.model.string().catch("")
              ]
            batching:
              count: 10000
              period: 1s
