services:
  kafka-clickhouse:
    image: jeffail/benthos:latest
    container_name: kafka-clickhouse
    ports:
      - 4197:4195
    restart: always
    environment:
      - TZ=Asia/Bangkok
    env_file:
      - .env
    volumes:
      - ./benthos.yaml:/benthos.yaml
      - ./log:/app/log
    entrypoint: ["sh", "-c", "/benthos -c /benthos.yaml 2>&1 | tee -a /app/log/benthos.log"]
    networks:
      - mms-network

networks:
  mms-network:
    external: true
