services:
  benthos:
    image: jeffail/benthos:latest
    container_name: benthos
    ports:
      - 4195:4195
    restart: always
    volumes:
      - ./benthos.yaml:/benthos.yaml
      - ./log:/app/log
    entrypoint: ["sh", "-c", "/benthos -c /benthos.yaml 2>&1 | tee -a /app/log/benthos.log"]
    networks:
      - mms-network

networks:
  mms-network:
    external: true