services:
  devicechecker:
    build: .
    image: mic/devicechecker:1.0.0
    container_name: devicechecker
    mem_limit: 1g
    cpus: 0.5
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./log:/app/log
    networks:
      - mms-network

networks:
  mms-network:
    external: true
