services:
  devicechecker:
    build: .
    image: mic/devicechecker:1.0.0
    container_name: devicechecker
    mem_limit: 256m
    cpus: 0.25
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    env_file:

      - ../.env
    volumes:
      - ./log:/app/log
    networks:
      - mms-network

networks:
  mms-network:
    external: true
